export const roomsElements = [
  {
    id: 1,
    name: 'Economy Box',
    type: 'Box',
    furnishings: {
      bed: false,
      blanket: true,
      toys: false,
    },
    price: 20.0,
    images: 'images/box1',
    description: '',
    recommendedFor: 'Small dogs',
    dogSizes: {
      small: true,
      medium: false,
      big: false,
    },
  },
  {
    id: 2,
    name: 'Standard Box',
    type: 'Box',
    furnishings: {
      bed: false,
      blanket: true,
      toys: false,
    },
    dogSizes: {
      small: true,
      medium: true,
      big: false,
    },
    price: 25.0,
    images: 'images/box2',
    description: '',
    recommendedFor: 'Medium dogs',
  },
  {
    id: 3,
    name: 'Big Box',
    type: 'Box',
    furnishings: {
      bed: false,
      blanket: true,
      toys: false,
    },
    dogSizes: {
      small: false,
      medium: true,
      big: true,
    },
    price: 30.0,
    images: 'images/box3',
    description: '',
    recommendedFor: 'Big dogs',
  },
  {
    id: 4,
    name: 'Comfort Room',
    type: 'room',
    furnishings: {
      bed: true,
      blanket: true,
      toys: false,
    },
    dogSizes: {
      small: true,
      medium: true,
      big: true,
    },
    price: 40.0,
    images: 'images/room1',
    description: '',
    recommendedFor: 'All dogs',
  },
  {
    id: 5,
    name: 'Premium Room',
    type: 'room',
    furnishings: {
      bed: true,
      blanket: true,
      toys: true,
    },
    dogSizes: {
      small: true,
      medium: true,
      big: true,
    },
    price: 70.0,
    images: 'images/room2',
    description: '',
    recommendedFor: 'All dogs',
  },
  {
    id: 6,
    name: 'Chill Room',
    type: 'room',
    furnishings: {
      bed: true,
      blanket: true,
      toys: false,
    },
    dogSizes: {
      small: true,
      medium: true,
      big: true,
    },
    price: 60.0,
    images: 'images/room3',
    description: '',
    recommendedFor: 'Stressed dogs',
  },
];
